# Generated by Django 5.2 on 2025-04-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
